---
apiVersion: newrelic.com/v1alpha2
kind: Instrumentation
metadata:
  name: newrelic-instrumentation-dotnet
spec:
  agent:
    language: dotnet
    # this sample uses the latest version of the .NET init container, but for a production app, you should use a specific version tag. 
    # See https://hub.docker.com/repository/docker/newrelic/newrelic-dotnet-init/general for a list of available tags.
    image: newrelic/newrelic-dotnet-init:latest